import random

def generate_advisor_report(vitals_data: dict) -> str:
    """
    Synthesizes vitals and vitality metrics into a premium AI health protocol.
    vitals_data keys: heart_rate, symmetry, radiance, stress_index (if any)
    """
    hr = vitals_data.get("heart_rate", 70)
    sym = vitals_data.get("symmetry", 80)
    rad = vitals_data.get("radiance", 80)
    
    # 1. Biological Age Estimation
    # Simple heuristic: Better symmetry/radiance and lower resting HR = younger bio-age
    # Baseline is assumed 30 for this mock-up
    bio_age_diff = (70 - hr) * 0.1 + (sym - 80) * 0.2 + (rad - 80) * 0.2
    bio_age = round(30 - bio_age_diff, 1)
    
    # 2. Longevity Forecast
    forecast = "Optimal" if bio_age < 30 else "Moderate Risk" if bio_age < 45 else "High Intervention Required"
    
    # 3. Nutrition & Exercise Protocols
    if hr > 85:
        exercise = "Focus on Zone 2 Cardio (walking, light cycling) to lower resting HR."
        food = "Increase Magnesium-rich foods (spinach, almonds) and cut stimulants like caffeine."
    else:
        exercise = "Incorporate HIIT (High-Intensity Interval Training) for 20 mins to boost mitochondrial health."
        food = "High Protein/Clean Fats (Avocado, Salmon) to maintain current radiance."

    # 4. Attractiveness & Vitality Index
    vibe_score = round((sym + rad) / 2, 1)
    attraction_tip = "Improve facial posture and hydration to boost Symmetry. Current Radiance is " + ("Excellent" if rad > 85 else "Standard") + "."

    # 5. Pain & Symptom Management
    pain_tip = "Based on your current Stress/HRV, localized muscle tension is likely in the neck. Use 5-min box breathing to alleviate."

    report = f"""
# 🧬 VitalLens Pro: AI Health Oracle Report

## 🕒 Biological Age Profile
* **Biological Age:** {bio_age} years
* **Longevity Forecast:** {forecast}
* **Vibe Score:** {vibe_score}/100

## 🥗 The Bio-Hacker Protocol
### Nutrition
{food}

### Exercise
{exercise}

## ✨ Aesthetics & Vitality
{attraction_tip}

## 🧘 Symptom Management
{pain_tip}

---
*Note: This report is generated by AI for wellness optimization. Consult a physician for medical concerns.*
"""
    return report.strip()
