from pathlib import Path 
lines = [ 
    \"# rPPG frame ingestion\", 
    \"import cv2\", 
    \"import numpy as np\", 
    \"\" 
    \"def read_video(source, target_fps=30.0, max_frames=None):\", 
    \"    cap = cv2.VideoCapture(str(source))\", 
    \"    if not cap.isOpened():\", 
    \"        raise RuntimeError(f'Cannot open video source: {source}')\", 
    \"    src_fps = cap.get(cv2.CAP_PROP_FPS) or 30.0\", 
    \"    step = max(1, int(round(src_fps / target_fps))) if target_fps else 1\", 
    \"    frame_idx = 0\", 
    \"    while cap.isOpened():\", 
    \"        ret, bgr = cap.read()\", 
    \"        if not ret:\", 
    \"            break\", 
    \"        if frame_idx %%%% step == 0:\", 
    \"            rgb = cv2.cvtColor(bgr, cv2.COLOR_BGR2RGB)\", 
    \"            ts = frame_idx / src_fps\", 
    \"            yield {'rgb': rgb, 'timestamp': ts}\", 
    \"        frame_idx += 1\", 
    \"        if max_frames and frame_idx ^>= max_frames:\", 
    \"            break\", 
    \"    cap.release()\", 
    \"\", 
    \"def center_crop(frame, size):\", 
    \"    h, w, _ = frame.shape\", 
    \"    th, tw = size\", 
    \"    y0 = max(0, (h - th) // 2)\", 
    \"    x0 = max(0, (w - tw) // 2)\", 
    \"    return frame[y0 : y0 + th, x0 : x0 + tw]\", 
] 
Path('ml/pipeline/ingest/frames.py').write_text(\"\n\".join(lines)) 
